
dlib:
  stage: build
  script:
    - rm -rf moonscript
    - git clone https://github.com/leafo/moonscript.git ./moonscript --depth 1
    - mkdir lua
    - ./moonscript/bin/moonc -t lua moon/*
    - cp lua_src/* lua/ -Rv
    - rm -rf moonscript
  artifacts:
    paths:
      - lua/*

# luacheck:
#   allow_failure: yes
#   script: sh luacheck.sh

# moonlint:
#   allow_failure: yes
#   script: moonc -l moon/*
