
before_script:
  - wget http://ru.archive.ubuntu.com/ubuntu/pool/universe/l/luajit/luajit_2.0.4+dfsg-1_amd64.deb
  - wget http://ru.archive.ubuntu.com/ubuntu/pool/universe/l/luarocks/luarocks_2.2.0+dfsg-2_all.deb
  - apt install ./luajit_2.0.4+dfsg-1_amd64.deb ./luarocks_2.2.0+dfsg-2_all.deb -y
  - luarocks install moonscript

dlib:
  stage: build
  script:
    - mkdir lua
    - moonc -t lua moon/*
    - cp lua_src/* lua/ -Rv
  artifacts:
    paths:
      - lua/*

# luacheck:
#   allow_failure: yes
#   script: sh luacheck.sh

# moonlint:
#   allow_failure: yes
#   script: moonc -l moon/*
