
before_script:
  - echo deb http://ru.archive.ubuntu.com/ubuntu/ xenial xenial-backports main restricted universe multiverse >>/etc/apt/sources.list
  - echo deb-src http://ru.archive.ubuntu.com/ubuntu/ xenial xenial-backports main restricted universe multiverse >>/etc/apt/sources.list
  - echo deb http://ru.archive.ubuntu.com/ubuntu/ xenial-backports main restricted universe multiverse >>/etc/apt/sources.list
  - echo deb-src http://ru.archive.ubuntu.com/ubuntu/ xenial-backports main restricted universe multiverse >>/etc/apt/sources.list
  - apt install luarocks -y
  - luarocks install moonscript

dlib:
  stage: build
  script:
    - mkdir lua
    - moonc -t lua moon/*
    - cp lua_src/* lua/ -Rv
  artifacts:
    paths:
      - lua/*

# luacheck:
#   allow_failure: yes
#   script: sh luacheck.sh

# moonlint:
#   allow_failure: yes
#   script: moonc -l moon/*
