
dlib:
  stage: build
  script:
    - rm -rf moonscript
    - rm -rf luajit
    - git clone https://github.com/leafo/moonscript.git ./moonscript --depth 1
    - git clone http://luajit.org/git/luajit-2.0.git ./luajit
    - cd luajit
    - git checkout v2.1
    - make
    - cd ../
    - mkdir lua
    - ./luajit/src/luajit moonscript/bin/moonc -t lua moon/*
    - cp lua_src/* lua/ -Rv
    - rm -rf moonscript
    - rm -rf luajit
  artifacts:
    paths:
      - lua/*

# luacheck:
#   allow_failure: yes
#   script: sh luacheck.sh

# moonlint:
#   allow_failure: yes
#   script: moonc -l moon/*
