
before_script:
  - apt install luajit -y
  - apt install luarocks -y
  - luarocks install moonscript

dlib:
  stage: build
  script:
    - mkdir lua
    - moonc -t lua moon/*
    - cp lua_src/* lua/ -Rv
  artifacts:
    paths:
      - lua/*

# luacheck:
#   allow_failure: yes
#   script: sh luacheck.sh

# moonlint:
#   allow_failure: yes
#   script: moonc -l moon/*
