AddCSLuaFile('autorun/client/dnotify/font_obj.lua')
AddCSLuaFile('autorun/client/dnotify/base_class.lua')
AddCSLuaFile('autorun/client/dnotify/templates.lua')
AddCSLuaFile('autorun/client/dnotify/animated_base.lua')
AddCSLuaFile('autorun/client/dnotify/slide_class.lua')
return AddCSLuaFile('autorun/client/dnotify/centered_class.lua')
